import os
env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

commons = os.environ['COMMONS']
#env['CCFLAGS'] += ['-g', '-Wall', '-std=c++11', '-O2', '-D GL_GLEXT_PROTOTYPES', '-D USE_E57', '-D NDEBUG', '-Wno-unknown-pragmas', '-Wno-deprecated-declarations', '-Wno-strict-aliasing', '-Wno-attributes', '-Wno-unused-local-typedefs']
#env['CCFLAGS'] += ['-g', '-Wall', '-std=c++11', '-O2', '-D GL_GLEXT_PROTOTYPES', '-D OMIT_NORMALS', '-D USE_E57', '-D NDEBUG', '-Wno-unknown-pragmas', '-Wno-deprecated-declarations', '-Wno-strict-aliasing', '-Wno-attributes', '-Wno-unused-local-typedefs']
env['CCFLAGS'] += ['-g', '-Wall', '-std=c++14', '-O2', '-D USE_CARTAN', '-D GL_GLEXT_PROTOTYPES', '-D USE_E57', '-D NDEBUG', '-Wno-unknown-pragmas', '-Wno-deprecated-declarations', '-Wno-strict-aliasing', '-Wno-attributes', '-Wno-unused-local-typedefs']
env['CPPPATH'] = ['.', '/usr/include/eigen3', '/usr/include/pcl-1.8', '/usr/local/include/graphene', '/usr/local/include', commons]
#env['LIBS']    = ['freeimageplus', 'E57RefImpl', 'E57SimpleImpl', 'xerces-c', 'time_conversion', 'pcl_common', 'pcl_io', 'pcl_keypoints', 'pcl_features', 'boost_system','boost_filesystem','GLEW', 'glut', 'Graphene']
env['LIBS']    = ['freeimageplus', 'E57RefImpl', 'E57SimpleImpl', 'xerces-c', 'time_conversion', 'pcl_common', 'pcl_io', 'pcl_keypoints', 'pcl_filters', 'pcl_features', 'boost_system','boost_filesystem','GLEW', 'glut', 'Graphene', 'OpenMeshCore', 'duraark', 'cartan', 'harmont']
env['LIBPATH'] = ['/usr/lib/OpenMesh', '/usr/local/lib']
env['SHLIBPREFIX'] = ''

env.SharedLibrary('visRegistration', ['visRegistration.cpp', 'Registration.cpp'])
